RedditClone/redditclone/config/routes.rb
Rails.application.routes.draw do
  get 'posts/new'
  get 'posts/edit'
  get 'posts/show'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users, only: [:new, :create, :show]
  resource :session, only: [:new, :create, :destroy]
  resources :subs 
  resources :posts do
    resources :comments, only: [:new]
  end

  resources :comments, only: [:create, :show]
end

RedditClone/redditclone/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

RedditClone/redditclone/app/models/comment.rb
class Comment < ApplicationRecord
  validates :content, presence: true

  belongs_to :user,
    primary_key: :id,
    foreign_key: :user_id,
    class_name: :User

  belongs_to :post,
    primary_key: :id,
    foreign_key: :post_id,
    class_name: :Post

  belongs_to :parent_comment,
    primary_key: :id,
    foreign_key: :parent_comment_id,
    class_name: :Comment,
    optional: true

  has_many :sub_comments,
    primary_key: :id,
    foreign_key: :parent_comment_id,
    class_name: :Comment

end

RedditClone/redditclone/app/models/post.rb
class Post < ApplicationRecord

    validates :title, presence: true

   

    belongs_to :user,
      primary_key: :id,
      foreign_key: :user_id,
      class_name: :User

    has_many :post_subs, 
      primary_key: :id,
      foreign_key: :post_id,
      class_name: :PostSub,
      inverse_of: :post,
      dependent: :destroy

     has_many :subs,
      through: :post_subs,
      source: :sub

    has_many :comments,
    primary_key: :id,
    foreign_key: :post_id,
    class_name: :Comment


end

RedditClone/redditclone/app/models/post_sub.rb
class PostSub < ApplicationRecord

  belongs_to :post, 
  primary_key: :id,
  foreign_key: :post_id,
  class_name: :Post

  belongs_to :sub, 
  primary_key: :id,
  foreign_key: :sub_id,
  class_name: :Sub
end

RedditClone/redditclone/app/models/sub.rb
class Sub < ApplicationRecord

  validates :title, :description, presence: true

  belongs_to :moderator,
    primary_key: :id,
    foreign_key: :moderator_id,
    class_name: :User

  has_many :post_subs, 
    primary_key: :id,
    foreign_key: :sub_id,
    class_name: :PostSub

  has_many :posts,
    through: :post_subs,
    source: :post
    # inverse_of: :sub,
    # dependent: :destroy
end

RedditClone/redditclone/app/models/user.rb
class User < ApplicationRecord

  validates :username, :password_digest, :session_token, presence: true
  validates :password, length: {minimum: 6, allow_nil: true}
  
  attr_reader :password

  after_initialize :ensure_session_token!


  def self.find_by_credentials(username, password)
    user = User.find_by(username: username)

    if user && user.is_password?(password)
      return user
    end
    nil
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def reset_session_token!
    self.session_token = SecureRandom.urlsafe_base64
    self.save!
    self.session_token
  end

  def ensure_session_token!
    self.session_token ||= SecureRandom.urlsafe_base64
  end

  has_many :moderated_subs,
    primary_key: :id,
    foreign_key: :moderator_id,
    class_name: :Sub

  has_many :posts,
      primary_key: :id,
      foreign_key: :user_id,
      class_name: :Post

  has_many :comments,
    primary_key: :id,
    foreign_key: :user_id,
    class_name: :Comment
end

RedditClone/redditclone/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  helper_method :current_user, :logged_in?, :all_subs

  def current_user
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  def login(user)
    @current_user = user
    session[:session_token] = user.reset_session_token!
  end

  def logout
    current_user.reset_session_token!
    session[:session_token] = nil
    redirect_to new_session_url
  end

  def logged_in?
    !!current_user
  end

  def require_login
    redirect_to new_session_url unless logged_in?
  end

  def all_subs
    Sub.all
  end

end

RedditClone/redditclone/app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def new
    @comment = Comment.new
  end

  def create
    @comment = Comment.new(comment_params)
    @comment.user_id = current_user.id
    if @comment.save
      redirect_to comment_url(@comment)
    else
      flash[:errors] = @comment.errors.full_messages
      render :new
    end
  end

  def show
    @comment = Comment.find(params[:id])
  end

  private

  def comment_params
    params.require(:comment).permit(:content, :parent_comment_id, :post_id)
  end

end

RedditClone/redditclone/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :require_login
  
  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id

    @post.save
    flash[:errors] = @post.errors.full_messages
    redirect_to post_url(@post)
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = current_user.posts.find(params[:id])

    if @post.update(post_params)
      flash[:errors] = "Post Successful!"
      redirect_to post_url(@post)
    else
      flash[:errors] = @post.errors.full_messages
      render :edit
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to subs_url
  end

  def new
    @post = Post.new
  end

  private

  def post_params
    params.require(:post).permit(:title, :url, :content, sub_ids:[])
  end
end

RedditClone/redditclone/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new

  end

  def create
    @user = User.find_by_credentials(params[:user][:username], params[:user][:password])

    if @user
      login(@user)
      redirect_to subs_url
    else
      flash[:errors] = "Invalid Credentials"
      render :new
    end
  end

  def destroy
    logout
  end
end

RedditClone/redditclone/app/controllers/subs_controller.rb
class SubsController < ApplicationController
  before_action :require_login

  def new
    @sub = Sub.new
  end

  def create
    @sub = Sub.new(sub_params)

    @sub.moderator_id = current_user.id
    if @sub.save
      redirect_to sub_url(@sub)
    else
      flash[:errors] = @sub.errors.full_messages
      render :new
    end
  end

  def index
    @subs = Sub.all
  end
  
  def show
    @sub = Sub.find(params[:id])
  
  end

  def edit
    @sub = Sub.find(params[:id])
  end

  def update
    @sub = current_user.moderated_subs.find(params[:id])

    if @sub.update_attributes(sub_params)
      redirect_to sub_url(@sub)
    else
      flash[:errors] =  @sub.errors.full_messages
      render :edit
    end
  end

  private

  def sub_params
    params.require(:sub).permit(:title, :description)
  end
end

RedditClone/redditclone/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      login(@user)
      redirect_to subs_url
    else
      flash[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end



  def user_params
    params.require(:user).permit(:username, :password)
  end
end

RedditClone/redditclone/app/helpers/application_helper.rb
module ApplicationHelper
end

RedditClone/redditclone/app/helpers/comments_helper.rb
module CommentsHelper
end

RedditClone/redditclone/app/helpers/posts_helper.rb
module PostsHelper
end

RedditClone/redditclone/app/helpers/sessions_helper.rb
module SessionsHelper
end

RedditClone/redditclone/app/helpers/subs_helper.rb
module SubsHelper
end

RedditClone/redditclone/app/helpers/users_helper.rb
module UsersHelper
end

RedditClone/redditclone/app/views/comments/new.html.erb
<h2>Create A Comment!</h2>

<form action="<%= comments_url %>" method="post">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">


  <label>Enter Comment:
    <textarea name="comment[content]" cols="30" rows="10"></textarea>
  </label>

  <input type="hidden" name="comment[post_id]" value="<%= params[:post_id]%>">

  <input type="submit" value="Add Comment">
</form>

RedditClone/redditclone/app/views/comments/show.html.erb
<%= @comment.content %>
<br>
<br>
<a href="<%= post_url(@comment.post) %>">Back to Post</a>

<form action="<%= comments_url %>" method="post">
  
  <input type="text" value="comment[body]">

  <input type="submit" value="Reply">
</form>

RedditClone/redditclone/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Redditclone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>

    <% if logged_in? %>
      <form action="<%= session_url%>" method = "POST">
        <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
        <input type="hidden" name="_method" value="DELETE">
        <input type="submit" value="Log Out">
      </form>
    <br>
      <a href="<%= subs_url %>">Sub Main Page</a>
  
    <% end %>

  
  
    <%= flash[:errors] %>
  </body>
</html>

RedditClone/redditclone/app/views/posts/edit.html.erb
<h1>Posts#edit</h1>
<p>Find me in app/views/posts/edit.html.erb</p>

RedditClone/redditclone/app/views/posts/new.html.erb
<h1>New Post</h1>

<form action="<%= posts_url %>" method="post">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

    <label>Title
      <input type="text" name="post[title]">
    </label>

    <label>URL
      <input type="text" name="post[url]">
    </label>

    <label>Content
      <textarea name="post[content]"></textarea>
    </label>

    <H2>SELECT ALL SUBS YOU WANT TO POST TO</H2>

    <input type="hidden" name="post[sub_ids][]" value="">

    <% all_subs.each do |sub| %>
     
      <input type="checkbox" name="post[sub_ids][]" value="<%= sub.id %>" ><%= sub.title %>
      <br>
    <% end %>
    

    <input type="submit" value="Create Post">
</form>

RedditClone/redditclone/app/views/posts/show.html.erb
<h1><%= @post.title %></h1>
<br>
  <a href="<%= @post.url %>"><%= @post.title %></a>
<br>
<%= @post.content %>


<ul>
<% @post.subs.each do |sub| %>
  
  
  <li><a href="<%= sub_url(sub)%>">
    <%= sub.title %>
  </a></li>


<% end %>
</ul>

<h3>Comments</h3>

<ul>
<% @post.comments.each do |comment| %>
  
  <% if comment.parent_comment_id.nil? %>
  
  <li><a href="<%= comment_url(comment)%>"><%= comment.content %></a></li>

  
  <% end %>
  
<% end %>
</ul>

RedditClone/redditclone/app/views/subs/index.html.erb
<h3>Welcome <%= current_user.username %> </h3>

<a href="<%= new_sub_url %>">Create New Sub</a>



<ul>
 <% all_subs.each do |sub| %>
     <li><a href="<%= sub_url(sub) %>"><%= sub.title %></a></li>
 <% end %>
</ul>

RedditClone/redditclone/app/views/subs/new.html.erb
<h2>Create Sub</h2>

<form action="<%= subs_url %>" method="post">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

   <label>Title
      <input type="text" name="sub[title]">
    </label>

    <label>Description
      <input type="text" name="sub[description]">
    </label>

   <input type="submit" value="Create Sub">
</form>

RedditClone/redditclone/app/views/subs/show.html.erb
<h2><%= @sub.title %></h2>

<%= @sub.description %>
<br><br>
<a href="<%= new_post_url%>">Create New Post!</a>

<% @sub.posts.each do |post| %>
<ul>
  <li>Title: <a href="<%= post_url(post) %>"><%= post.title %></a></li>
  <li>Content: <%= post.content %></li>
  <a href="<%= new_post_comment_url(post)%>">Add Comment!</a>
  </ul>-----------------------
<% end %>

RedditClone/redditclone/app/views/users/new.html.erb
<h2>Sign Up</h2>

Already have a account? <a href="<%= new_session_url %>">Sign In</a>
  
<form action="<%= users_url %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <label>Username
    <input type="text" name="user[username]">
  </label>

  <label>Password
    <input type="text" name="user[password]">
  </label>

  <input type="submit" value="Sign Up">
</form>

RedditClone/redditclone/app/views/users/show.html.erb
<h2><%= @user.username %></h2>